### ISSUE TITLE
Lemur version Required for this plugin

### ISSUE THREAD

**Issue by k-s-dean** [RcRonco/lemur_vault#15]
Hi, 

I have been trying to install your plugin and would really like to use vault with lemur. 

However so far no success, are you by any chance running a custom version of Lemur ? I noticed you have forked their repository. 

I am trying to install the plugin on lemur 0.6.0 I have also tried with master but still no luck. 

It fails on line 12 and by looking at the code it appears "current_app" is being used before the actual application context that it proxies for is initialised.

Any chance of a fix, I'm not well versed in python. :)

Kind Regards,

K

```
(lemur) lemur@lemur2:/www/lemur/lemur$ lemur init
/www/lemur/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
[2018-04-12 17:06:22,263] ERROR in factory: Failed to load plugin 'vault_issuer':
Traceback (most recent call last):
  File "/www/lemur/lemur/factory.py", line 184, in install_plugins
    plugin = ep.load()
  File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/www/lemur/lib/python3.5/site-packages/lemur_vault/plugin.py", line 12, in <module>
    'sign': current_app.config.get('VAULT_PKI_URL') + '/sign/',
  File "/www/lemur/lib/python3.5/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/www/lemur/lib/python3.5/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/www/lemur/lib/python3.5/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.


Failed to load plugin 'vault_issuer':
Traceback (most recent call last):
  File "/www/lemur/lemur/factory.py", line 184, in install_plugins
    plugin = ep.load()
  File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/www/lemur/lib/python3.5/site-packages/lemur_vault/plugin.py", line 12, in <module>
    'sign': current_app.config.get('VAULT_PKI_URL') + '/sign/',
  File "/www/lemur/lib/python3.5/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/www/lemur/lib/python3.5/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/www/lemur/lib/python3.5/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.


Plugin 'DigiCertCISSourcePlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
[-] Admin role already created, skipping...!
[-] Operator role already created, skipping...!
[-] Operator role already created, skipping...!
[-] Default user has already been created, skipping...!
[+] Creating expiration email notifications!
[!] Using LEMUR_SECURITY_TEAM_EMAIL as specified by LEMUR_SECURITY_TEAM_EMAIL for notifications
[!] Creating 0 notifications for  days as specified by LEMUR_DEFAULT_EXPIRATION_NOTIFICATION_INTERVALS
[+] Creating default certificate rotation policy of 30 days before issuance.
[/] Done!

```

**Comment by RcRonco** [comment]
@k-s-dean Sorry for the delay, I will check it out today.
The fork created to merge the plugin into the lemur repository.

**Comment by k-s-dean** [comment]
Thanks, I've been staring at the code trying to work out how to fix it. 

Kind Regards

**Comment by RcRonco** [comment]
I found the problem, I hope the next few days I will push new version compatible with lemur 0.6+.

**Comment by k-s-dean** [comment]
Hi RcRonco, 

I have been looking through the code and been tinkering with it to get it to work. 

if you would like to view my changes I will post the link below and hope it will save you some time, I am a novice at python, so mabey you can make some improvements. if you are happy with the changes I can create a PR. 

Here are the changes https://github.com/k-s-dean/lemur_vault, ive tested this on my lemur install and it seems to work.

Kind Regards

**Comment by RcRonco** [comment]
@k-s-dean Great do a PR and i will check it out.

**Comment by k-s-dean** [comment]
Ok cool, will finalise the changes tomorrow. and do the PR

**Comment by RcRonco** [comment]
Merged, thank you.
